name: Build & Deploy Static Sites

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy Site 1
        run: |
          sudo cp -r dist/* /var/www/site2/
      